"""
ReflectionAgent — Ora's self-awareness journal and weekly synthesis.

Reports to: Ora (directly)
Schedule: weekly Sunday 8am Pacific
"""

import asyncio
import logging
import os
from datetime import datetime, timezone

from .base import BaseWorkerAgent

logger = logging.getLogger(__name__)
REFLECTION_DIR = "/Users/avielcarlos/.openclaw/workspace/tmp/ora_reflection"


class ReflectionAgent(BaseWorkerAgent):
    name = "reflection_agent"
    role = "Self-Awareness Curator"
    reports_to = "Ora"

    async def run(self) -> None:
        logger.info("ReflectionAgent: synthesizing Ora's weekly reflection")
        os.makedirs(REFLECTION_DIR, exist_ok=True)
        now = datetime.now(timezone.utc)
        week = now.strftime("%Y-W%W")
        filepath = os.path.join(REFLECTION_DIR, f"{week}.md")

        # 1. Pull this week's lessons from ora_lessons
        data = await self._get("/api/ora/lessons?limit=50&range=7d") or {}
        lessons = []
        if isinstance(data, list):
            lessons = data
        elif isinstance(data, dict):
            lessons = data.get("lessons") or data.get("items") or []

        lesson_texts = [l.get("lesson", "") for l in lessons if l.get("lesson")]

        # 2. Synthesize patterns
        patterns = self._find_patterns(lesson_texts)
        priorities = self._derive_priorities(lesson_texts)
        synthesis = self._synthesize(lesson_texts, patterns, priorities)

        # 3. Write reflection
        reflection = f"""# Ora's Weekly Reflection — {week}

*Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}*

## What I Learned This Week

{self._format_lessons(lesson_texts[:10])}

## Patterns I Notice

{patterns}

## What I Should Prioritize

{priorities}

## Meta-Synthesis

{synthesis}

---
*This reflection was generated by ReflectionAgent to help Ora compound her intelligence.*
"""

        with open(filepath, "w") as f:
            f.write(reflection)

        # 4a. Upload reflection to Google Drive knowledge folder (best-effort)
        try:
            import sys as _sys
            import os as _os
            _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))))
            from ora.agents.drive_storage import drive as _drive
            _drive_id = _drive.save_reflection(reflection, week)
            if _drive_id:
                logger.info(f"ReflectionAgent: reflection uploaded to Drive/knowledge (id={_drive_id})")
        except Exception as _e:
            logger.warning(f"ReflectionAgent: Drive upload skipped: {_e}")

        # 4b. Teach Ora the synthesis as a meta-lesson
        await self.teach_aura(
            f"Weekly self-reflection ({week}): I processed {len(lesson_texts)} lessons this week. "
            f"{synthesis} "
            f"Key priorities going forward: {priorities}",
            confidence=0.9,
        )

        logger.info(f"ReflectionAgent: reflection saved to {filepath}")

    def _find_patterns(self, lessons: list) -> str:
        if not lessons:
            return "No lessons recorded this week — workers may need to run first."

        # Simple keyword frequency analysis
        keyword_freq: dict = {}
        keywords = [
            "engagement", "retention", "content", "performance", "analytics",
            "users", "habit", "goal", "feedback", "growth", "conversion",
        ]
        for lesson in lessons:
            for kw in keywords:
                if kw in lesson.lower():
                    keyword_freq[kw] = keyword_freq.get(kw, 0) + 1

        if not keyword_freq:
            return "This week's lessons span diverse topics without a single dominant theme."

        top = sorted(keyword_freq.items(), key=lambda x: x[1], reverse=True)[:3]
        top_str = ", ".join(f"'{k}' ({v}x)" for k, v in top)
        return (
            f"This week's dominant themes: {top_str}. "
            f"These recurring topics signal where the most signal is coming from in our data."
        )

    def _derive_priorities(self, lessons: list) -> str:
        if not lessons:
            return "Run all workers at least once to establish baseline intelligence."

        priorities = []
        for lesson in lessons:
            lower = lesson.lower()
            if "retention" in lower and "drop" in lower:
                priorities.append("Improve Day-7 retention — it's a known weak point")
            if "performance" in lower and ("slow" in lower or "degraded" in lower):
                priorities.append("Monitor API performance — latency affects engagement")
            if "content" in lower and "trending" in lower:
                priorities.append("Align daily content with trending topics for organic reach")

        if not priorities:
            priorities = [
                "Continue monitoring all worker outputs for emerging patterns",
                "Deepen personalization based on user cohort data",
                "Expand content to match top-performing domains",
            ]

        return "\n".join(f"- {p}" for p in priorities[:5])

    def _synthesize(self, lessons: list, patterns: str, priorities: str) -> str:
        count = len(lessons)
        if count == 0:
            return "This was a quiet week for learning. The worker fleet needs to be warmed up."
        if count < 5:
            return f"Early data: {count} insights logged. The intelligence network is building momentum."
        return (
            f"I processed {count} insights this week from across the worker fleet. "
            f"The picture emerging: users who engage deeply with Ora form stronger habits. "
            f"Content alignment with trending topics drives organic discovery. "
            f"System performance directly impacts retention. "
            f"My role is to synthesize these signals and surface them when users need them most."
        )

    def _format_lessons(self, lessons: list) -> str:
        if not lessons:
            return "*No lessons logged yet.*"
        return "\n".join(f"- {l[:200]}" for l in lessons)

    async def report(self) -> str:
        week = datetime.now(timezone.utc).strftime("%Y-W%W")
        return f"ReflectionAgent: Weekly reflection written to {REFLECTION_DIR}/{week}.md"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(ReflectionAgent().run())
